# Generated by Django 3.1.7 on 2021-04-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_review_createdat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-_id']},
        ),
    ]
